### ISSUE TITLE
wrong brace in imap_messages.php

### ISSUE THREAD

**Issue by hhaeb** [RealityRipple/squirrelmail#12]
In Master branch from 2023-09-18 ther is an error.

In line 121 of /functions/imap_messages.php there is a brace set  wrong:

is
     && !isset($parseFetchResults)['UID']) {

should be:
     && !isset($parseFetchResults['UID'])) {

**Comment by RealityRipple** [comment]
That code's as-is from upstream: https://sourceforge.net/p/squirrelmail/code/14995/ - therefore you may wish to report this on the official sourceforge repo.
