### ISSUE TITLE
RFC6331: Moving DIGEST-MD5 to Historic

### ISSUE THREAD

**Issue by Neustradamus** [RealityRipple/squirrelmail#2]
20 November 2008: CRAM-MD5 to Historic:
- https://tools.ietf.org/html/draft-ietf-sasl-crammd5-to-historic-00

29 June 2017: CRAM-MD5 to Historic:
- https://tools.ietf.org/html/draft-zeilenga-luis140219-crammd5-to-historic-00

July 2011: RFC6331: Moving DIGEST-MD5 to Historic:
- https://tools.ietf.org/html/rfc6331

There are now:
- July 2010: RFC5802: Salted Challenge Response Authentication Mechanism (SCRAM): SASL and GSS-API Mechanisms: https://tools.ietf.org/html/rfc5802 (SCRAM-SHA-1 and SCRAM-SHA-1-PLUS)
- November 2015: RFC7677: SCRAM-SHA-256 and SCRAM-SHA-256-PLUS: Simple Authentication and Security Layer (SASL) Mechanisms: https://tools.ietf.org/html/rfc7677

Linked to:
- https://github.com/jult/SquirrelMail/issues/2
- https://github.com/hannob/squirrelpatches/issues/2

**Comment by RealityRipple** [comment]
I will mark CRAM-MD5 and DIGEST-MD5 as **Historic and no longer considered secure** where appropriate, but for optimal compatibility, they're not going to be removed.

Note that these changes will _not_ apply to Trunk.

**Comment by Neustradamus** [comment]
@RealityRipple: Thanks for these changes :)
