### ISSUE TITLE
enable TLSv1.2

### ISSUE THREAD

**Issue by rubo77** [RealityRipple/squirrelmail#4]
Can you please add support for TLSv1.2?

**Comment by RealityRipple** [comment]
**TLS** and **STARTTLS** are already supported by SquirrelMail. See the `$use_imap_tls` and `$use_smtp_tls` configuration values, and the PHP entry on [SSL Context](https://www.php.net/manual/en/context.ssl.php).
You can see in `deliver/Deliver_SMTP.class.php` and `functions/imap_general.php` that it is already set up to use "ssl://" which will use the latest TLS version your PHP install will support.

The mail_fetch plugin uses "tls://" directly instead, though, so if you use that plugin and wish for it to support TLS 1.2, you can modify line 193 of `plugins/mail_fetch/class.mail_fetch.php`.

**Comment by rubo77** [comment]
I use the standard debian installation on Debian jessie. There is no such file `plugins/mail_fetch/class.mail_fetch.php`, only:

```
ll plugins/mail_fetch/
insgesamt 96
-rw-r--r-- 1 root root 20821 Jan  2  2012 class.POP3.php
-rw-r--r-- 1 root root  1840 Jan  2  2012 config_example.php
-rw-r--r-- 1 root root 11150 Aug  1  2019 fetch.php
-rw-r--r-- 1 root root  5793 Feb  8  2012 functions.php
-rw-r--r-- 1 root root   498 Jan  2  2012 index.php
-rw-r--r-- 1 root root 21567 Aug  1  2019 options.php
-rw-r--r-- 1 root root  5293 Jun 21  2010 README
-rw-r--r-- 1 root root 10849 Jan  2  2012 setup.php
```

**Comment by rubo77** [comment]
I tried to use this repository instead and edited line 193 to `tlsv1.2://`, but I am not able to connect to IMAP with the same settings as before in the default debian config

**Comment by RealityRipple** [comment]
This is not the standard package or anything like it. The official project is hosted on SourceForge. This project is a cleaned version of the 1.5.2 branch.

And read the linked entry on SSL Context above. `tlsv1.2://` is not a valid protocol at all. The protocol you want is `ssl://`.
