### ISSUE TITLE
locales repo for translations

### ISSUE THREAD

**Issue by MPolleke** [RealityRipple/squirrelmail#5]
Hi,
Thank you very much for keeping SquirrelMail somewhat alive.

Is it possible to also make an import of the locales repository from SVN? That way translations can be updated and maybe added. I am using Dutch myself and it is quite up to date, but I can imagine other languages might need more work.

**Comment by RealityRipple** [comment]
Given the directory structure, it'd probably be best to make the Locales folder an entirely separate repository. Unfortunately, that's a bit beyond the scope of this repository and my usage, and I don't really want to provide something I have no intention (or means) to support.

**Comment by MPolleke** [comment]
Hi Andrew,
That is a valid answer :)

I will see if I want to go that route. I will be playing with the locales a bit and see where I get.
