### ISSUE TITLE
Can’t Open This Page Frames

### ISSUE THREAD

**Issue by ghost** [RealityRipple/squirrelmail#6]
just checkout the latest squirrelmail and after login, the page with the 2 frames cannot be shown:

Firefox Developer Edition Can’t Open This Page

To protect your security, atraxrobustus.com will not allow Firefox Developer Edition to display the page if another site has embedded it. To see this page, you need to open it in a new window.

**Comment by ghost** [comment]
Content Security Policy: The page’s settings blocked the loading of a resource at https://atraxrobustus.com/squirrelmail/src/webmail.php (“frame-ancestors”).

**Comment by ghost** [comment]
ok, i found my issue, missing config setting
the $provider_uri  in config.php must be set like: 
$provider_uri     = 'https://atraxrobustus.com';

**Comment by RealityRipple** [comment]
I made a note of this in commit 1cd1fed06bfd0f26a78932ba129ecdd0c0147e08, but I should eventually add a new config variable specifically for this feature.
