### ISSUE TITLE
X-Frame-Options 

### ISSUE THREAD

**Issue by dozeen** [RealityRipple/squirrelmail#7]
Note: The Content-Security-Policy HTTP header has a frame-ancestors directive which obsoletes this header for supporting browsers.

![Schermata da 2021-02-11 20-59-04](https://user-images.githubusercontent.com/4419010/107691937-69322200-6cac-11eb-9354-af97c662c4bc.png)

Qualcuno di voi si e` trovato un errore come il mio ?

**Comment by RealityRipple** [comment]
Duplicate of #6

Please set the `$provider_uri` value in your config. For advanced details, see commit 1cd1fed.
